### ISSUE TITLE
More than one hyphen in model name causes faulty class naming.

### ISSUE THREAD

**Issue by Liblastic** [devgeniem/dustpress#104]
If you name model `page-test-forum.php`.
Then the models class should be named `PageTest_forum` to make it work. This should be changed to be in format `PageTestForum`?

**Comment by Liblastic** [comment]
To be more specific this doesn't seem to be an issue with pages but this happens for example with taxonomies.

**Example:**
template name: taxonomy-forum-test.php
model name: TaxonomyForum_test

**Comment by Nomafin** [comment]
Fixed.
