### ISSUE TITLE
Prevent infinite loops in navigation items

### ISSUE THREAD

**Issue by onnimonni** [devgeniem/dustpress#11]
Sometimes we want to add the same page many times in the same navigation. At the moment this causes infinite loop and the php process runs out of memory.

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /var/www/project/vendor/devgeniem/dustpress/helpers/menu.php on line 176
```
![screen shot 2016-12-30 at 13 34 34](https://cloud.githubusercontent.com/assets/5691777/21566217/b18831d4-cea9-11e6-97ef-bc8a05d0e91a.png)

**Comment by Nomafin** [comment]
This is now fixed.
