### ISSUE TITLE
Dustpress Debugger setting many cookies

### ISSUE THREAD

**Issue by VivekManglani** [devgeniem/dustpress#13]
When I have Dustpress Debugger activated, every load seems to be setting a separate cookie everytime. Perhaps there are many "session_start()" calls?

![screen shot 2017-01-04 at 5 33 20 pm](https://cloud.githubusercontent.com/assets/6572849/21637951/2941cfe8-d2a4-11e6-8912-cd0fc931e6db.png)

As soon as I deactivate the debugger, these set-cookie headers disappear.

**Comment by Nomafin** [comment]
We'll look at this one as well as soon as possible.

**Comment by Nomafin** [comment]
The fix was pushed to the DustPress Debugger repository. Please comment here if it fixed it on your project as well, so that we could close this issue.
