### ISSUE TITLE
A single 0 in clauses breaks .dust files.

### ISSUE THREAD

**Issue by zArubaru** [devgeniem/dustpress#27]
```
{?variable}1{:else}0{/variable}

{?variable}0{:else}1{/variable}

{?variable}0{:else}0{/variable}
```

All of the above produce a similar error:

`Dust error: Missing end tag for ?variable (line 1 character 13)`

These do **not** produce the error:
```
{?variable}1{:else} 0{/variable}

{?variable}00{:else}1{/variable}

{?variable}
    0
{:else}
    0
{/variable}
```

**Comment by Nomafin** [comment]
This is a problem of the Dust-PHP library, not DustPress itself.
