### ISSUE TITLE
The data filtering for component data is not working for flexible components

### ISSUE THREAD

**Issue by villesiltala** [devgeniem/dustpress#28]
Version: 1.5.13

When using DustPress Components as flexible ACF fields, the `dustpress/data/component=` filter does not work (data.php:30). The item key passed after the filter prefix is the key of the flexible field, not the component field. Thus the component data filter function is not run.

**Comment by villesiltala** [comment]
This seems to occur if the main field group name is not defined as `c`.

**Comment by Nomafin** [comment]
`data.php` is now a part of DustPress Components plugin, where the issue has also been fixed.
