### ISSUE TITLE
Better support for the loop in the content helper

### ISSUE THREAD

**Issue by villesiltala** [devgeniem/dustpress#45]
Could the `content` helper setup post data while looping through posts on an archive page? Currently the helper runs `setup_postdata` only if it is used on a single article page and the `data` parameter is omitted.

The helper could accept the following parameters:
- `data` the content data as a string
- `post` a post object
- `id` a post id

**Comment by Nomafin** [comment]
This has been implemented with the ability to give an `id` parameter.
