### ISSUE TITLE
Add a 'getkey' helper

### ISSUE THREAD

**Issue by villesiltala** [devgeniem/dustpress#5]
Add a core helper that prints out a value from an array or an object by the passed key. The syntax could be as follows:
```
{@getkey map=array/object key=key /}
```
If the key _is no set_, an empty string is printed.

**Comment by Nomafin** [comment]
Can you elaborate a bit what do you mean with this?

**Comment by villesiltala** [comment]
This enables you to dynamically get a value from an object.


Print out a string:
```
{my_string}
```
Print out a value from an object with the string as the key:
```
{@getkey map=my_object key=my_string /}
```

**Comment by villesiltala** [comment]
This is against Dust philosophy. We will not implement a dynamic key getter. If you need this kind of logic, there is something wrong with you and your model structure. ;)

Not implemented.
