### ISSUE TITLE
Pass partial usage data into DustPress Debugger

### ISSUE THREAD

**Issue by villesiltala** [devgeniem/dustpress#8]
Pass a data block into the Debugger which displays all found partials and data whether they are used or not. List used templates first.

Example data:

```
{
   "used:" [
      "shared/my-partial": "/var/www/my-site/content/themes/my-theme/partials/shared/my-partial.dust"
   ]
}
```

**Comment by Nomafin** [comment]
This has been added to version 1.3.2 of DustPress Debugger.
