### ISSUE TITLE
get_permalink() fails inside get_acf_post() when $acfpost is empty

### ISSUE THREAD

**Issue by visahakkarainen** [devgeniem/dustpress#87]
https://github.com/devgeniem/dustpress/blob/master/classes/query.php#L134

get_permalink fails when $acfpost is empty. This might happen when id is still found from database but the actual post is deleted (e.g. relation field might still have this data).

https://github.com/devgeniem/dustpress/blob/master/classes/query.php#L104
get_post() won't find anything if the post is deleted.

**Comment by villesiltala** [comment]
Will be fixed in: https://github.com/devgeniem/dustpress/pull/88
